SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE*S.SALES) AS SALES
FROM BOOK B
JOIN AUTHOR A 
  ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S 
  ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
  AND S.SALES_DATE <  TO_DATE('2022-02-01', 'YYYY-MM-DD')
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;