SELECT O.ANIMAL_ID,O.ANIMAL_TYPE,O.NAME
FROM ANIMAL_INS I 
INNER JOIN ANIMAL_OUTS O 
    ON I.ANIMAL_ID= O.ANIMAL_ID	
where I.SEX_UPON_INTAKE like 'Intact%' and (O.SEX_UPON_OUTCOME like 'Spayed%' or O.SEX_UPON_OUTCOME like 'Neutered%')
order by O.ANIMAL_ID asc;