SELECT HISTORY_ID,CAR_ID,DATE_FORMAT(START_DATE,'%Y-%m-%d') as START_DATE,DATE_FORMAT(END_DATE,'%Y-%m-%d') AS END_DATE,
case
    when DATEDIFF(END_DATE,START_DATE)+1 >= 30 THEN '장기 대여'
    else '단기 대여'
        end RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
where DATE_FORMAT(START_DATE,'%Y-%m') = '2022-09'
order by HISTORY_ID desc;
