SELECT
    CAR_ID, 
    TO_CHAR(ROUND(AVG(END_DATE - START_DATE + 1), 1), 'FM99990.0')
    AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING
    ROUND(AVG(END_DATE - START_DATE + 1), 1) >= 7
ORDER BY
    ROUND(AVG(END_DATE - START_DATE + 1), 1) DESC, 
    CAR_ID DESC;