SELECT  ROUTE,CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE,CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
order by SUM(D_BETWEEN_DIST)desc;