SELECT CAR_ID,
case
when max(
    CASE
    WHEN END_DATE>=DATE '2022-10-16' and START_DATE<= DATE '2022-10-16' THEN 1
    else 0
end) = 1
    then '대여중'
    else '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID
ORDER BY CAR_ID DESC;
