SELECT MEMBER_ID,MEMBER_NAME,GENDER,TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD') as DATE_OF_BIRTH
from MEMBER_PROFILE
where TLNO is not null and EXTRACT(MONTH FROM DATE_OF_BIRTH) = 3 and GENDER = 'W'
order by MEMBER_ID asc;
