SELECT U.USER_ID,U.NICKNAME, SUM(B.PRICE) as TOTAL_SALES
from USED_GOODS_BOARD B
INNER JOIN USED_GOODS_USER U
    on B.WRITER_ID = U.USER_ID
where B.STATUS = 'DONE'
group by U.USER_ID,U.NICKNAME
having SUM(B.PRICE) >= 700000
order by TOTAL_SALES asc;

