SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) as HOUR,COUNT(*) as COUNT
from ANIMAL_OUTS
where TO_NUMBER(TO_CHAR(DATETIME,'HH24')) between 9 and 19
group by TO_NUMBER(TO_CHAR(DATETIME,'HH24'))
order by HOUR;