SELECT F.ITEM_ID,F.ITEM_NAME,F.RARITY
FROM ITEM_INFO F
JOIN (
    SELECT T.ITEM_ID
    FROM ITEM_INFO I
inner join ITEM_TREE T
ON I.ITEM_ID = T.PARENT_ITEM_ID AND I.RARITY = 'RARE'
) M ON M.ITEM_ID = F.ITEM_ID
ORDER BY F.ITEM_ID DESC;