SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA CHILD
JOIN ECOLI_DATA PARENT
ON CHILD.PARENT_ID = PARENT.ID
where (CHILD.GENOTYPE & PARENT.GENOTYPE) = PARENT.GENOTYPE
order by CHILD.ID asc;