SELECT
  YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
  M.max_size - E.SIZE_OF_COLONY AS YEAR_DEV,
  E.ID
FROM ECOLI_DATA E
JOIN (
  SELECT
    YEAR(DIFFERENTIATION_DATE) AS yr,
    MAX(SIZE_OF_COLONY) AS max_size
  FROM ECOLI_DATA
  GROUP BY YEAR(DIFFERENTIATION_DATE)
) M ON M.yr = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC, E.ID ASC;